#pragma once

typedef struct
{
	CoolingType coolingtype;
	int LowerLimit;
	int UpperLimit;
}CoolingInfo;

#define NORMAL_COOLING_LOWERLIMIT 0
#define NORMAL_COOLING_UPPERLIMIT 35
#define HIGH_ACTIVE_COOLING_LOWERLIMIT 0
#define HIGH_ACTIVE_COOLING_UPPERLIMIT 45
#define MEDIUM_ACTIVE_COOLING_LOWERLIMIT 0
#define MEDIUM_ACTIVE_COOLING_UPPERLIMIT 40
#define MAXIMUM_COOLING_TYPE 3
