#include <stdio.h>
#include "config.h"

//array which holds limit config list 
const CoolingInfo CoolingInfoTable[]= {
    {NORMAL_COOLING , NORMAL_COOLING_LOWERLIMIT,NORMAL_COOLING_UPPERLIMIT},
    {HIGH_ACTIVE_COOLING,HIGH_ACTIVE_COOLING_LOWERLIMIT,HIGH_ACTIVE_COOLING_UPPERLIMIT},
    {MEDIUM_ACTIVE_COOLING,MEDIUM_ACTIVE_COOLING_LOWERLIMIT,MEDIUM_ACTIVE_COOLING_UPPERLIMIT},
};
